name: Fetch Upstream

on:
  schedule:
    - cron: '30 5,17 * * *'

jobs:
  fetch-upstream:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Fetch Upstream
      uses: bdougie/fetch-upstream@master
      with:
        upstream: rails/rails
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
